rule A:
    input:
        "empty.csv"
    output:
        "full.tsv"
    run:
        with open("empty.csv", "r") as f:
            f = f.read()
            f = f.splitlines()
        
        header = f[0].split(",")
        numbers = range(1, 28)

        final_data = [*header, *numbers]

        with open("full.tsv", "w+") as o:
            for i in range(0, 30, 3):
                o.write(f"{final_data[i]}\t{final_data[i+1]}\t{final_data[i+2]}\n")
